# Generated by Django 6.0.1 on 2026-02-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chamados',
            new_name='Tickets',
        ),
    ]
