# Generated by Django 6.0.1 on 2026-02-20 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_chamados_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_status', to='tickets.status'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
