# Generated by Django 6.0.1 on 2026-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_tickets_status_alter_tickets_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
