# Generated by Django 6.0.1 on 2026-02-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_tickets_data_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
